### ISSUE TITLE
android.support.design.widget.NavigationView is not found !!!

### ISSUE THREAD

**Issue by tavishjain** [IOSD/YFHR_Android_App#19]
System says that cannot resovle symbol NavigationView . The problem in this is that it is not able to resolve design .

**Comment by tavishjain** [comment]
![untitled](https://user-images.githubusercontent.com/31106411/32225914-00b9720a-be6d-11e7-8627-8b860f8f8a30.png)

Here is the screenshot

**Comment by tavishjain** [comment]
On searching on the internet , I found that adding compile 'com.android.support:appcompat-v7:23.1.1'

compile 'com.android.support:design:23.1.1

in the build.gradle file would solve the issue . But this didnt help either .

**Comment by deepanshib** [comment]
compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
add these lines in dependencies and sync....
try this... and if still doesnot work then do send the screenshot of your build gradle file.. maybe the issue is because of your minimum build version  is different

**Comment by deepanshib** [comment]
#19

![yfhrissue18](https://user-images.githubusercontent.com/17212810/33097466-4a564d60-cf30-11e7-9072-65104d0d4668.png)
![navbar](https://user-images.githubusercontent.com/17212810/33097737-1dcf2f54-cf31-11e7-8a7e-8e4a5ad4dbf4.jpeg)

There is no such kind of error. Your gradle has not completely built maybe that's why it cannot resolve navigationview

**Comment by tavishjain** [comment]
My gradle build has completed . Even tried adding those lines in the gradle file . Still it says that can't resolve Navigation bar
